# -*- coding: utf-8 -*-
"""Clean All FT HT_Rev

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-jVA0TwOeeVDBZRbhlzGTmPeLCXQYWI
"""

!pip install sastrawi optuna tqdm

import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from torch.cuda.amp import autocast, GradScaler
from transformers import BertTokenizer, BertForSequenceClassification
from torch.optim import AdamW
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import f1_score, classification_report
from sklearn.utils import resample
from random import choice
from tqdm import tqdm
import optuna
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
import gc
import os
import time

# Anti memory leak & idle
torch.backends.cudnn.benchmark = True
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# ------------------------------
# Load dataset
# ------------------------------
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/dataset/preprocessed/data_clean.csv", sep=",")

df["Sentimen"] = pd.to_numeric(df["Sentimen"], errors="coerce")
df = df.dropna(subset=["Sentimen"])
df = df[df["Sentimen"].isin([-1, 0, 1])]

print("Distribusi label asli:")
print(df["Sentimen"].value_counts())

# Encode label
label_map = {-1:0,0:1,1:2}
inv_label_map = {0:-1,1:0,2:1}
df["label_enc"] = df["Sentimen"].map(label_map)

# Split 80-20 (Train-Test)
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["label_enc"],
    random_state=42
)

print("TRAIN:", train_df.shape, "TEST:", test_df.shape)

# ------------------------------
# Tokenizer & Dataset
# ------------------------------
tokenizer = BertTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

class TextDataset(Dataset):
    def __init__(self, df, max_len=64):
        self.texts = df["Konten"].astype(str).tolist()
        self.labels = df["label_enc"].tolist()
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = tokenizer(self.texts[idx], truncation=True, padding="max_length",
                        max_length=self.max_len, return_tensors="pt")
        item = {k:v.squeeze() for k,v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

# ------------------------------
# Load WordNet Indonesia
# ------------------------------
def load_wordnet_indonesia(file_path):
    """
    Load WordNet Indonesia dari file tab (wn-ind-def.tab atau edaindo.tab) ke dictionary.
    Format file: synset_id <tab> POS <tab> LEMMA
    Dictionary output: {lemma: [sinonim1, sinonim2, ...]}
    """
    word2synonyms = {}
    synsets = {}

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().lower().split("\t")
            if len(parts) < 4:
                continue
            synset_id = parts[0]
            lemma = parts[3]

            # Simpan lemma per synset
            if synset_id not in synsets:
                synsets[synset_id] = []
            synsets[synset_id].append(lemma)

    # Buat dictionary kata → list sinonim
    for synset, lemmas in synsets.items():
        for lemma in lemmas:
            # sinonim = semua kata lain di synset
            syns = [l for l in lemmas if l != lemma]
            if syns:
                word2synonyms[lemma] = syns

    print(f"Loaded {len(word2synonyms)} words with synonyms from WordNet Indonesia")
    return word2synonyms

# Contoh load
wordnet_file = "/content/drive/MyDrive/dataWN/edaindo.tab"  # ganti path sesuai lokasi file
wordnet_indo = load_wordnet_indonesia(wordnet_file)

# ------------------------------
# Oversampling
# ------------------------------
# ROS
def random_oversample(df):
    max_n = df["label_enc"].value_counts().max()
    dfs=[]
    for lbl in df["label_enc"].unique():
        dfs.append(resample(df[df["label_enc"]==lbl], replace=True, n_samples=max_n, random_state=42))
    return pd.concat(dfs).reset_index(drop=True)

def synonym_replacement_wn(text, n=1):
    """Ganti kata dengan sinonim dari WordNet Indo jika ada."""
    if not isinstance(text, str):
        text = "" if pd.isna(text) else str(text)
    words = text.split()

    for _ in range(n):
        idxs = [i for i, w in enumerate(words) if w in wordnet_indo and wordnet_indo[w]]
        if not idxs:
            break
        idx = choice(idxs)
        words[idx] = choice(wordnet_indo[words[idx]])

    return " ".join(words)

def random_deletion(text, p=0.1):
    """
    Randomly delete words with probability p.
    Aman untuk NaN, float, dan string kosong.
    """
    if not isinstance(text, str):
        text = "" if pd.isna(text) else str(text)

    words = text.split()
    if len(words) == 0:
        return text

    new_words = [w for w in words if np.random.rand() > p]

    # kalau semua kata terhapus, kembalikan teks asli
    if len(new_words) == 0:
        return text

    return " ".join(new_words)

def eda_augment_wn_minority(df, num_aug=2):
    """
    EDA (Synonym Replacement + Random Deletion)
    HANYA untuk kelas minoritas
    """
    augmented_texts, augmented_labels = [], []

    # Hitung distribusi kelas
    label_counts = df["label_enc"].value_counts()
    majority_label = label_counts.idxmax()

    for label, count in label_counts.items():
        # ❗ Skip kelas mayoritas
        if label == majority_label:
            continue

        df_label = df[df["label_enc"] == label]

        for text in df_label["Konten"]:
            text = "" if pd.isna(text) else str(text)

            for _ in range(num_aug):
                t = synonym_replacement_wn(text, n=1)  # SR
                t = random_deletion(t, p=0.1)          # RD

                augmented_texts.append(t)
                augmented_labels.append(label)

    new_df = pd.DataFrame({
        "Konten": augmented_texts,
        "label_enc": augmented_labels
    })

    # Gabungkan data original + hasil EDA minoritas
    return pd.concat([df, new_df]).reset_index(drop=True)




def oversample_data(df, method="ros"):
    if method=="ros":
        return random_oversample(df)
    elif method=="eda":
        return eda_augment_wn_minority(df)
    elif method=="none":
        return df
    else:
        return df

# ==============================
# CEK DISTRIBUSI DATA
# ORIGINAL vs ROS vs EDA
# ==============================

def show_distribution(df, title="DATA"):
    print(f"\n=== {title} ===")
    print("Total data:", len(df))
    print(df["label_enc"].value_counts().sort_index())

    # persentase
    print("\nPersentase:")
    print((df["label_enc"].value_counts(normalize=True)*100).round(2))


# 1️⃣ ORIGINAL (TRAIN SET SAJA)
show_distribution(train_df, "ORIGINAL TRAIN DATA")


# 2️⃣ RANDOM OVERSAMPLING
train_ros = random_oversample(train_df)
show_distribution(train_ros, "AFTER RANDOM OVERSAMPLING (ROS)")


# 3️⃣ EDA + WordNet Indonesia
train_eda = eda_augment_wn_minority(train_df)
show_distribution(train_eda, "AFTER EDA (WordNet Indo)")


# 4️⃣ Perbandingan ringkas
summary = pd.DataFrame({
    "Original": train_df["label_enc"].value_counts(),
    "ROS": train_ros["label_enc"].value_counts(),
    "EDA": train_eda["label_enc"].value_counts()
}).fillna(0).astype(int)

print("\n=== SUMMARY PERBANDINGAN ===")
display(summary)

# ------------------------------
# Device & scaler
# ------------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
scaler = GradScaler()

def objective(trial, df_train, method="ros", kfold=5):
    lr = trial.suggest_float("lr", 1e-5, 5e-5, log=True)
    batch_size = trial.suggest_categorical("batch_size", [8, 16])
    epochs = trial.suggest_int("epochs", 2, 3)

    X = df_train[["Konten"]]
    y = df_train["label_enc"]

    skf = StratifiedKFold(n_splits=kfold, shuffle=True, random_state=42)
    fold_scores = []

    for fold, (tr_idx, val_idx) in enumerate(skf.split(X, y), start=1):
        print(f"\n--- Fold {fold}/{kfold} ---")

        # Split data
        X_tr, X_val = X.iloc[tr_idx], X.iloc[val_idx]
        y_tr, y_val = y.iloc[tr_idx], y.iloc[val_idx]

        # Oversampling (TRAIN ONLY)
        df_tr = pd.DataFrame({
            "Konten": X_tr["Konten"],
            "label_enc": y_tr
        })
        df_tr = oversample_data(df_tr, method)

        # Dataloaders
        train_loader = DataLoader(
            TextDataset(df_tr),
            batch_size=batch_size,
            shuffle=True,
            num_workers=2,
            pin_memory=True,
            persistent_workers=True
        )

        val_loader = DataLoader(
            TextDataset(pd.DataFrame({
                "Konten": X_val["Konten"],
                "label_enc": y_val
            })),
            batch_size=16,
            num_workers=2,
            pin_memory=True,
            persistent_workers=True
        )

        # Model & optimizer
        model = BertForSequenceClassification.from_pretrained(
            "indobenchmark/indobert-base-p1",
            num_labels=3
        ).to(device)

        optimizer = AdamW(model.parameters(), lr=lr)

        # =====================
        # Training + HEARTBEAT
        # =====================
        for epoch in range(epochs):
            print(f"Epoch {epoch+1}/{epochs} (running)")  # heartbeat
            model.train()
            for batch in train_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                optimizer.zero_grad()
                with autocast():
                    loss = model(**batch).loss
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()

        # ==========
        # Validation
        # ==========
        model.eval()
        preds, trues = [], []
        with torch.no_grad():
            for batch in val_loader:
                batch = {k: v.to(device) for k, v in batch.items()}
                out = model(**batch)
                preds.extend(out.logits.argmax(1).cpu().numpy())
                trues.extend(batch["labels"].cpu().numpy())

        f1 = f1_score(trues, preds, average="macro")
        print(f"Fold {fold} Macro F1: {f1:.4f}")
        fold_scores.append(f1)

        # =========================
        # CLEAN GPU & RAM PER FOLD
        # =========================
        del model, optimizer, train_loader, val_loader
        torch.cuda.empty_cache()
        gc.collect()
        time.sleep(2)

    return np.mean(fold_scores)

# ------------------------------
# Run Optuna & Train final
# ------------------------------
def run_method(df_train, df_test, method="ros", n_trials=3, kfold=5):
    print(f"\n=== RUNNING HYPERPARAM TUNING FOR {method.upper()} ===")

    # ===== OPTUNA CHECKPOINT (RUNTIME SAFE) =====
    storage_name = f"sqlite:///{method}_optuna_cleanall.db"
    study = optuna.create_study(
        direction="maximize",
        study_name=f"{method}_study",
        storage=storage_name,
        load_if_exists=True
    )

    study.optimize(
        lambda t: objective(t, df_train, method, kfold),
        n_trials=n_trials
    )

    print(f"\nBest params: {study.best_params}")
    print(f"Best CV mean F1: {study.best_value:.4f}")

    # Final train on full train set with best params
    params = study.best_params
    df_final = oversample_data(df_train, method)
    final_loader = DataLoader(
        TextDataset(df_final),
        batch_size=params["batch_size"],
        shuffle=True
    )

    final_model = BertForSequenceClassification.from_pretrained(
        "indobenchmark/indobert-base-p1",
        num_labels=3
    ).to(device)

    optimizer = AdamW(final_model.parameters(), lr=params["lr"])

    print(f"\n=== FINAL TRAINING ON FULL TRAIN SET ({method.upper()}) ===")
    for epoch in range(params["epochs"]):
        print(f"Epoch {epoch+1}/{params['epochs']}")
        final_model.train()
        for batch in tqdm(final_loader, desc="Training"):
            batch = {k:v.to(device) for k,v in batch.items()}
            optimizer.zero_grad()
            with autocast():
                loss = final_model(**batch).loss
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()

    torch.save(final_model.state_dict(), f"{method}_final.pt")
    print(f"Model saved: {method}_final.pt")

    # Evaluate on test
    test_loader = DataLoader(TextDataset(df_test), batch_size=16)
    final_model.eval()
    preds, trues = [], []
    with torch.no_grad():
        for batch in test_loader:
            batch = {k:v.to(device) for k,v in batch.items()}
            out = final_model(**batch)
            preds.extend(out.logits.argmax(1).cpu().numpy())
            trues.extend(batch["labels"].cpu().numpy())

    print(f"\n=== TEST EVALUATION ({method.upper()}) ===")
    print(classification_report(trues, preds, target_names=["Negatif","Netral","Positif"]))

    cm = confusion_matrix(trues, preds, labels=[0,1,2])
    plt.figure(figsize=(6,5))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Blues",
        xticklabels=["Negatif","Netral","Positif"],
        yticklabels=["Negatif","Netral","Positif"]
    )
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(f"Confusion Matrix ({method.upper()})")
    plt.show()

    return study.best_value, f1_score(trues, preds, average="macro")

# Baseline (tanpa balancing)
# f1_base_cv, f1_base_test = run_method(train_df, test_df, method="none")

# ROS
# f1_ros_cv, f1_ros_test = run_method(train_df, test_df, method="ros")

# EDA
f1_eda_cv, f1_eda_test = run_method(train_df, test_df, method="eda")

# ==============================
# FINAL SUMMARY
# ==============================
print("\n=== SUMMARY HASIL EKSPERIMEN ===")

#print(f"BASELINE (No Balancing)")
#print(f"CV Macro F1   : {f1_base_cv:.4f}")
#print(f"Test Macro F1 : {f1_base_test:.4f}")

#print("\nRANDOM OVERSAMPLING (ROS)")
#print(f"CV Macro F1   : {f1_ros_cv:.4f}")
#print(f"Test Macro F1 : {f1_ros_test:.4f}")

print("\nEDA (WordNet Indonesia)")
print(f"CV Macro F1   : {f1_eda_cv:.4f}")
print(f"Test Macro F1 : {f1_eda_test:.4f}")

summary_df = pd.DataFrame({
    "Method": ["EDA"],
    "CV Macro F1": [f1_eda_cv],
    "Test Macro F1": [f1_eda_test]
})

print("\n=== SUMMARY TABLE ===")
print(summary_df)

#summary_df = pd.DataFrame({
 #   "Method": ["Baseline", "ROS", "EDA"],
  #  "CV Macro F1": [f1_base_cv, f1_ros_cv, f1_eda_cv],
   # "Test Macro F1": [f1_base_test, f1_ros_test, f1_eda_test]
#})

print("\n=== SUMMARY TABLE ===")
print(summary_df)